### PR TITLE
Simplify `golden-ratio-mode'

### PR DESCRIPTION
**Pull request by abo-abo**

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
Thanks, but now golden-ratio is not happening when splitting windows.
Also, golden-ratio-exclude-modes have no more effects.

**Comment by abo-abo** [comment]
> Thanks, but now golden-ratio is not happening when splitting windows.

No problem, just needs one more advice.

> Also, golden-ratio-exclude-modes have no more effects.

Fixed up, that logic was lost in the merge conflict.

**Comment by thierryvolpiatto** [comment]
Ok looks good now, thanks.

**Comment by thierryvolpiatto** [comment]
Oleh Krehel <notifications@github.com> writes:

>     Thanks, but now golden-ratio is not happening when splitting windows.
>    
> No problem, just needs one more advice.
>
>     Also, golden-ratio-exclude-modes have no more effects.
>    
> Fixed up, that logic was lost in the merge conflict.

Now scrolling in Gnus is broken...

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by abo-abo** [comment]
> Now scrolling in Gnus is broken...

It works fine for me.

**Comment by thierryvolpiatto** [comment]
Oleh Krehel <notifications@github.com> writes:

>     Now scrolling in Gnus is broken...
>    
> It works fine for me.

I mean gnus-summary-scroll-up (press RET repetitively from summary
buffer).

Maybe it is working in emacs-25 due to a difference in select-window,
but it is broken in emacs-24.4/5.

Disabling golden-ratio-mode let it working, switching to version 1.0 of
golden ratio fix the problem too.

Please try to fix, otherwise I will look into this ASAP (not the time
now).

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by abo-abo** [comment]
> I mean gnus-summary-scroll-up (press RET repetitively from summary buffer). Maybe it is working in emacs-25 due to a difference in select-window, but it is broken in emacs-24.4/5.

Its scrolls fine in 24.5.2. Although it's weird to have golden-ratio on at all for gnus, since it makes the summary (which I like to keep small) much larger than the article.

**Comment by thierryvolpiatto** [comment]
> Its scrolls fine in 24.5.2.

No it doesn't. I have opened an issue #49 .

**Pull request merged**
